- hosts: <%= appName %>_managers[0]
  name: "** <%= appName %> k8s Master  **"
  become: yes
  become_user: root
  serial: 1
  roles:
    - <%= appName %>-master

- hosts: <%= appName %>_workers
  name: "** <%= appName %> k8s Worker **"
  gather_facts: false
  become: yes
  become_user: root
  serial: 1
  roles:
    - <%= appName %>-worker
