---
- name: Inculde Setup.
#  include_tasks: <% if (os === "ubuntu") { %> setup-debian.yml <% } else if (os === "centos") { %> setup-redhat.yml <% } %>
<% if (os === "ubuntu") { %>
  include_tasks: setup-debian.yml
<% } %>
<% if (os === "centos") { %>
  include_tasks: setup-redhat.yml
<% } %>

- name: Install Docker.
  package:
      name: "{{ docker_package }}"
      state: "{{ docker_package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
      name: docker
      state: "{{ docker_service_state }}"
      enabled: "{{ docker_service_enabled }}"

- name: Install Docker Compose.
  include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- name: Ensure User in Docker Group.
  include_tasks: docker-users.yml
  when: docker_users | length > 0

- name: Ensure Base Kubernetes
  apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
  with_items:
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni

- name: Ensure swap is off
  become: yes
  command: "swapoff -a"

- name: Remove swap from fstab
  become: yes
  lineinfile:
      dest: /etc/fstab
      regexp: 'swap'
      state: absent
